### ISSUE TITLE
Google sheets documentation

### ISSUE THREAD

**Issue by akanshaaa19** [glific/docs#194]
the documentation for google sheets need to be updated because we changed the ui for writing to sheets

instead of putting the sheet name and column name like `Sheet1!A10:D` we need to put it separately now
<img width="693" alt="image" src="https://github.com/user-attachments/assets/c33c37bf-3b9c-4950-b3ee-45f4a3fe7279">

**Comment by mahajantejas** [comment]
https://github.com/glific/docs/pull/222

**Comment by SangeetaMishr** [comment]
https://github.com/glific/docs/pull/222
