### ISSUE TITLE
to capture date-time in google sheets

### ISSUE THREAD

**Issue by mahajantejas** [glific/docs#195]
We don't have @calendar.current_datetime property. You can use custom expression node and use this expression to get both date and time  - <%= DateTime.now!("Asia/Kolkata") |> Calendar.strftime("%Y/%m/%d %H:%M:%S") %>

refer for more details: https://discord.com/channels/717975833226248303/1272765622622879837

**Comment by SangeetaMishr** [comment]
https://github.com/glific/docs/pull/207
