### ISSUE TITLE
misleading: in facebook verification page verification 

### ISSUE THREAD

**Issue by djv03** [glific/docs#30]
this is refer to issue in document of in facebook verification page verification 
![image](https://github.com/glific/docs/assets/93385841/df4b6df7-0e4e-45ad-af13-024cc695782b)
the number should be referred to step 28 but it is referring in step 25.

**Comment by adityakode** [comment]
I would love to work on this !

**Comment by djv03** [comment]
PR already submitted :(,  try another issues
