### ISSUE TITLE
Wait for response node- Any of the words acceptance criteria

### ISSUE THREAD

**Issue by KrishnaDwibhashi2** [glific/docs#69]
Right now documentation for wait for response node doesn't have notes that the words seperated by comma or space are considered as seperate words. Please add that to the documentation.

Reference chat- https://discord.com/channels/717975833226248303/1174574292663537744/1174627923228114954

@aravind-glific

**Comment by SangeetaMishr** [comment]
this has been added to the documentationhttps://glific.github.io/docs/docs/Product%20Features/Flows/Flow%20Actions/Wait%20for%20the%20contact%20to%20respond hence, closing this
