### ISSUE TITLE
Template messaging disabled error while orgs are trying to send HSM messages

### ISSUE THREAD

**Issue by KrishnaDwibhashi2** [glific/docs#72]
If users are getting below error while sending HSM messages, it can be because of 2 reasons-
![image](https://github.com/glific/docs/assets/122982753/9790d13b-3b6d-4e48-b47b-cc6941c905ee)

1)It might be because Template messaging is not enabled on Gupshup
![image](https://github.com/glific/docs/assets/122982753/d31e3fd5-8c60-492f-a754-70b7fb9a5e44)

2) It could also be because of user not opting in (i.e their settings not updated) 

@aravind-glific please update documentation to this

**Comment by SangeetaMishr** [comment]
this is completed here : https://github.com/glific/docs/pull/189
