### ISSUE TITLE
No documentation on Analytics/ Internal dashboard page

### ISSUE THREAD

**Issue by mahajantejas** [glific/docs#96]
<img width="602" alt="Screenshot 2024-02-14 at 4 08 12 PM" src="https://github.com/glific/docs/assets/141305477/8f72429f-6e9d-401d-a678-0f7dd05394c3">

**Comment by mahajantejas** [comment]
https://github.com/glific/docs/pull/224

**Comment by SangeetaMishr** [comment]
https://github.com/glific/docs/pull/224
